version: "3.3"

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  # db:
  #   image: mysql
  #   restart: unless-stopped
  #   command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
  #   volumes:
  #     - db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD="${DB_ROOT_PW}"
  #     - MYSQL_PASSWORD="${DB_USER_PW}"
  #     - MYSQL_DATABASE=g2e_users
  #     - MYSQL_USER=g2e_useraccount
  #   networks:
  #     frontend:
  #       ipv4_address: 172.26.0.10
  #       aliases:
  #         - db
  

  
  brokrbackend:
    build: ./backend
    restart: unless-stopped
    networks:
      frontend:
        ipv4_address: 172.26.0.2
  
  # presentr:
  #  build: ./presentr
  #  restart: unless-stopped
  #  networks:
  #   frontend:
  #     ipv4_address: 172.26.0.3

volumes:
  db:
